### ISSUE TITLE
Le chargement ne démarre pas

### ISSUE THREAD

**Issue by cdlr27** [yy0931/vscode-mplstyle#12]
Type: <b>Feature Request</b>

import numpy as np # installed with matplotlib
import matplotlib.pyplot as plt

matplotlib n'est pas chargé

Extension version: 1.13.3
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by cdlr27** [comment]
J'ai installé mplstyle (Matplotlib)  : réponse : ModuleNotFoundError: No module named 'Numpy'
 et installé Python Image Preview : réponse idem

**Comment by yy0931** [comment]
The extension requires matplotlib and numpy to be installed. Try running `pip3 install matplotlib` and `py -m pip install matplotlib` in the command prompt.
