### ISSUE TITLE
development mode

### ISSUE THREAD

**Issue by story645** [yy0931/vscode-mplstyle#18]
Hi, I'm a huge fan of this extension -  it just helped me find what was breaking most of my tests. 

Would it be feasible to have a right click `add temporarily/for this session` option? The motivation is PRs that add new rcParams (e.g. https://github.com/matplotlib/matplotlib/pull/26854) where it's minor but a little "huh what?" to see a rcParam erroring cause it's new.

**Comment by yy0931** [comment]
I couldn't quite understand what you mean by `add temporarily/for this session`. Are you suggesting a feature that would allow you to disable syntax errors for specific lines using non-standard property names, similar to eslint's `// eslint-disable-next-line` or Pylance's `# type: ignore`?

**Comment by story645** [comment]
> . Are you suggesting a feature that would allow you to disable syntax errors for specific lines using non-standard property names, similar to eslint's // eslint-disable-next-line or Pylance's # type: ignore?

I think so. Like here I'd like for a quick-fix option to disable errors on this line:
![image](https://github.com/yy0931/vscode-mplstyle/assets/1300499/50510736-e935-400b-8aae-11a8f78d2a19)

**Comment by yy0931** [comment]
In the latest version of the extension, you can disable the error via the Quick Fix.

**Comment by story645** [comment]
Thanks so much!
